# Generated by Django 6.0.2 on 2026-02-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radicacion', 'initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicado',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
