# Generated by Django 6.0.2 on 2026-03-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radicacion', '0001_alter_radicado_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocorrespondencia',
            name='codigo',
            field=models.CharField(default='YES', max_length=10),
            preserve_default=False,
        ),
    ]
