# Generated by Django 6.0.2 on 2026-02-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radicado',
            name='destinatario',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='radicado',
            name='direccion',
            field=models.CharField(choices=[('recibido', 'Correo Recibido'), ('enviado', 'Correo Enviado')], default='recibido', max_length=10),
        ),
        migrations.AddField(
            model_name='radicado',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
    ]
