# Generated by Django 6.0.2 on 2026-02-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radicacion', '0002_radicado_destinatario_radicado_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radicado',
            name='codigo_barras',
            field=models.ImageField(blank=True, null=True, upload_to='codigos/'),
        ),
    ]
