# Generated by Django 6.0.2 on 2026-03-11 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radicacion', '0002_tipocorrespondencia_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='radicado',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='radicado',
            name='numero',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tipocorrespondencia',
            name='codigo',
            field=models.CharField(default='DOC', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='radicado',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='CER', null=True, on_delete=django.db.models.deletion.PROTECT, to='radicacion.empresa'),
        ),
    ]
