# Generated by Django 6.0.2 on 2026-02-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radicacion', '0004_perfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='usuario',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='radicado',
            name='numero',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
