# Generated by Django 6.0.2 on 2026-03-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radicacion', '0004_historialestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicado',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
